# ## see https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/cmd/otelcontribcol/builder-config.yaml
# dist:
#   name: nms-otelcollector
#   description: Local NMS OpenTelemetry Collector binary
#   output_path: ./build
#   version: 0.67.0-dev
#   otelcol_version: 0.67.0
# exporters:
#   - gomod: go.opentelemetry.io/collector/exporter/loggingexporter v0.67.0
#   - gomod: go.opentelemetry.io/collector/exporter/otlphttpexporter v0.67.0
#   - gomod: go.opentelemetry.io/collector/exporter/otlpexporter v0.67.0
# otlp/2:
# receivers:
#   - gomod: go.opentelemetry.io/collector/receiver/otlpreceiver v0.67.0

# processors:
#   - gomod: go.opentelemetry.io/collector/processor/batchprocessor v0.67.0
dist:
  name: otel-collector
  description: Basic OTel Collector distribution
  output_path: ./otel-collector
  otelcol_version: 0.67.0

exporters:
  - gomod:
      go.opentelemetry.io/collector/exporter/loggingexporter v0.67.0

# processors:
#   - gomod:
#       go.opentelemetry.io/collector/processor/batchprocessor v0.67.0

receivers:
  - gomod:
      go.opentelemetry.io/collector/receiver/otlpreceiver v0.67.0